"""fixed initial Database Setup

Revision ID: ba0b75ba22ae
Revises: 8f2963215174
Create Date: 2026-05-03 10:54:56.727868

"""
from pgvector.sqlalchemy import Vector
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0b75ba22ae'
down_revision: Union[str, Sequence[str], None] = '8f2963215174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('notes', sa.Column('embedding', Vector(768), nullable=True))
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'embedding')
    # ### end Alembic commands ###
