"""added the none essentials. tags, source url create and updated at

Revision ID: d19e3d236dec
Revises: ba0b75ba22ae
Create Date: 2026-05-13 22:12:57.149692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19e3d236dec'
down_revision: Union[str, Sequence[str], None] = 'ba0b75ba22ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        'notes',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()')
        )
    )
    op.add_column(
        'notes',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()')
        )
    )
    op.add_column(
        'notes',
        sa.Column('tags', sa.String(), nullable=True)
    )
    op.add_column(
        'notes',
        sa.Column('source_url', sa.String(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'created_at')
    op.drop_column('notes', 'source_url')
    op.drop_column('notes', 'tags')
    # ### end Alembic commands ###
